AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CFTargetGrp:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: 'cf-tg'
      VpcId: !ImportValue VpcId
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Tags:
        - Key: 'Name'
          Value: 'cf-task-tg'
      Targets:
        -  Id: !ImportValue EC2id
           Port: 80 
  CFTaskLB:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: 'cf-task-lb'
      Scheme: internet-facing
      Subnets:
        - !ImportValue PubSub1Id
        - !ImportValue PubSub2Id
      SecurityGroups:
        - !ImportValue SGid
      Type: application
      Tags:
        - Key: Name
          Value: 'cf-task-lb'
  CFLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref CFTargetGrp
      LoadBalancerArn: !Ref CFTaskLB
      Port: 80
      Protocol: HTTP
Outputs:
  ALBHostName:
    Description: 'CF Task LB Hostname'
    Value: !GetAtt CFTaskLB.DNSName
    Export:
      Name: "LBdns"
  TGarn:
    Description: 'ARN of the Target Group created'
    Value: !GetAtt CFTargetGrp.TargetGroupArn
    Export:
      Name: "TGarn"